### ISSUE TITLE
Logo / Favicon

### ISSUE THREAD

**Issue by xy2z** [xy2z/dopenote#1]

**Comment by calvinmorett** [comment]
## Favicon based on Brand Logo
![image](https://user-images.githubusercontent.com/11654917/53043965-b087ce00-3457-11e9-9f31-6b4130f0af4f.png)

Maybe should utilize post-it yellow-ish color, familiar, easy on the eyes.

- Logo Concept
https://codepen.io/CalvinMorett/full/QYYEPq

**Comment by xy2z** [comment]
Nice and simple. I like it, especially the hover animation. 
Can you make a 16x16 favicon so we can test it in browser and mobile?

**Comment by calvinmorett** [comment]
16x16 Favicon. Basic color scheme, yellow, black, background transparent

- Static
https://raw.githubusercontent.com/calvinmorett/dopenote/master/favicon.ico

- Animated Version
https://imgeasy.com/images/f4RT.gif

**Comment by xy2z** [comment]
Relevant: https://stackoverflow.com/questions/48956465/favicon-standard-2019-svg-ico-png-and-dimensions

**Comment by xy2z** [comment]
I'm not so sure about the yellow, it's not a good contrast with the white background in the tabs..

How about orange? 
Or black background, and a yellow "N" in the favicon?

**Comment by calvinmorett** [comment]
Okay, I’ll do some styles you can pick from!

**Comment by calvinmorett** [comment]
![fl06.png](https://imgeasy.com/images/fl06.png)

**Comment by xy2z** [comment]
My favourite is the `#FFC90E` square with the black line. Looks good on white and dark grey (sidebar)

Will you make a PR?

**Comment by xy2z** [comment]
@calvinmorett  I was thinking, wouldn't it make more sense if the letter is a 'D' instead of 'N'?

**Comment by calvinmorett** [comment]
Sort of, part of the favicon/logo already ~ The D is the right edge part
wrapping the note ;)

With that said, I can change it up to whatever you need.

**Comment by xy2z** [comment]
Im not sure its clear enough. I think most will expect a D since it starts with D.
But, I really like the N logo ;) it looks so good.

I have tried changing it to D but it just doesnt look good, imo..
Any thoughts?

Do you know a good font for a D? 

Another thought was to have no letter and maybe a symbol/icon instead?

**Comment by xy2z** [comment]
Here's some Google Fonts I liked for the logo
Atm "Carter One" is my favorite, with `letter-spacing: -0.1em`
![](https://i.imgur.com/maFlpOd.jpg)

**Comment by calvinmorett** [comment]
I have based some new ideas off of the favicon I designed. I'll upload them as I flesh it out more and you can let me know if it could make more sense based on that to tie it together. 

As far as the fonts, I think my favorite is Abril. It looks cleaner than most of those other fonts, and carries the notion of a serif used in books & writing in general.

**Comment by xy2z** [comment]
Cool, I was afraid you had lost interest :)

I like them all generally, but the reason I like Carter One more is because the 'D' is probably the most unique, so people will recocnize the 'D' and think of Dopenote and not other logos that start with D.
But, if the 'D' has a background/color like the one you did above, it becomes more unique and distinctive.

Looking forward to seeing what you come up with

**Comment by calvinmorett** [comment]
Haven’t lost interest! But I do feel that I need to focus on one thing at a
time instead of trying to be involved with everything on the project :)


Here is where my heads at with how the fav icon can influence some of he ui.

**Comment by calvinmorett** [comment]
Where I’m at with the fav icon, and there is a logo animation in there
somewhere... it has both initials from that one 6x5 grid

**Comment by xy2z** [comment]
Some quick thoughts
- I'd like the sidebar to be in the left side, but as we talked about this will be customizable by the user later
- I don't think tags and color will be part of the first release, as I want to keep it somewhat simple, but it's a great idea for later features.
- I don't think "App" (settings and updates" should take so much space, Notebooks, notes and the editor should be as primary as possible, and everything else should be as minimized as possible (user, settings, updates
- I like the logo, but maybe it's a bit too simplistic to be recognizable?
- I think all notebooks should be visible from the layout without having to go through a modal, so users can quickly change between notebooks and notes, and it's easier to drag a note to a new notebook (like the custom layout, like Notejoy)

**Comment by calvinmorett** [comment]
Have you see. Editorjs?

**Comment by xy2z** [comment]
No i dont know editorjs

**Comment by calvinmorett** [comment]
Sorry unrelated to your other comment, but https://editorjs.io. Only brought it up because I thought it would be at least interesting to you, it was to me.

To go over your above points:
- Okay, yeah I understand your idea about the side bar, it's familiar to users as well.
- I find the best way for me to organize my notes is through color values, easier to ID for me, but that's understandable, it's probably a lot to get involved in adding.
- Yeah, I'll run it back and implement your suggestions to the UI
- I'll flesh out a better, quality example and we can continue to reiterate - maybe this 'issue' should be Logo instead of Favicon, it's kind of gone past that point wouldn't you agree?
- Yeah all notebooks make sense, I guess when I was rendering that sketch that was just a quick-access type idea, and I agree and would want a modal window display for all notebooks too!

**Comment by xy2z** [comment]
I renamed this issue to Logo / Favicon
And I think you misunderstood, i don't like the modal - i'd prefer to show all notebooks. Maybe if the user has ALOT a modal would be good. But if there's just 10-15 notebooks, IMO they should be visible without a modal.

**Comment by xy2z** [comment]
New Favicon done.

Sorry I had to change the nice "N" favicon you did with a "D" so it's matching the logo and name.
I just want to get an alpha out soon-ish, so I just had to mix something together - so I'm very open to new suggestions.. Especially in the app layout and design, which will probably be a never ending story - but also if you have good ideas on improving the logo or favicon :)

Thanks for the work though!

**Comment by calvinmorett** [comment]
Have some new ideas for a logo/branding 
https://imgeasy.com/images/165b7025e74c39a19595a2ff098ae9a7.png

**Comment by xy2z** [comment]
I really like the one on the right in the 2nd row, the orange D with a pen in it.
Maybe it should be a bit bigger so it's easier to see from the favicon?

**Comment by calvinmorett** [comment]
Edits, trying to draw down on that one in variations.

![image](https://user-images.githubusercontent.com/11654917/62631124-344a4f80-b8fe-11e9-870a-a614b14aecba.png)

**Comment by xy2z** [comment]
My favorite is the first (top left) ❤️

**Comment by calvinmorett** [comment]
Here's the orange versions:
![image](https://user-images.githubusercontent.com/11654917/62905735-c8bb1480-bd39-11e9-9b2c-c5e2c29dca48.png)

Here you can scale the logo:
https://codepen.io/CalvinMorett/full/rNBOmdB


This is the color scheme, the orange is for the branding and some of other parts of the design, mainly creating new notebooks and notes.
https://codepen.io/CalvinMorett/pen/RXzqLp

These can be easily integrated with CSS variables, and the best part is we can integrate it over all paths if we're unhappy with the colors later in the process.
```

	--red:#b00000;
	--orange:#d2482c;
	--orange2:#f66001;
	--orange3:#e69800;
	--green:#018c31;
	--green2:#6c9c6c;
	--gray:#969696;
	--gray2:#6f7477;
	--lite:#d1d0ce;
	--dark:#292a2e;

```
