### ISSUE TITLE
Tiptap code highlight (npm)

### ISSUE THREAD

**Issue by xy2z** [xy2z/dopenote#103]
https://tiptap.scrumpy.io/code-highlighting - See bottom of page how to setup.

Use the default theme

Let me know if you have any questions.

**Comment by MJunaidAhmad** [comment]
And Working on this one too. :)

**Comment by xy2z** [comment]
I'm opening this up for others, since @MJunaidAhmad is working on #121

**Comment by MJunaidAhmad** [comment]
Since I have completed the Social login Feature so I am returning back to this one.

**Comment by xy2z** [comment]
@MJunaidAhmad how's it going? 😃

**Comment by MJunaidAhmad** [comment]
I have integrated the code block for now and its working... but somehow the css is not being applied by tiptap... 
![image](https://user-images.githubusercontent.com/12229238/67067864-621b0280-f191-11e9-9647-a9ac05ef9346.png) 
Since you already integrated the tiptap... so any guidance?

**Comment by xy2z** [comment]
I have fixed it, if you're interested see how I added the css in the `webpack.mix` file
https://github.com/xy2z/dopenote/commit/06b6d0a03c1f48193f70f4b489f91fc97f58c689
