### ISSUE TITLE
OAuth - Social Media Register/Login

### ISSUE THREAD

**Issue by xy2z** [xy2z/dopenote#107]
https://laravel.com/docs/6.x/socialite

https://medium.com/employbl/add-login-with-google-to-your-laravel-app-d2205f01b895

First priority is Google, Twitter and Facebook - if it's easy, also add GitHub.

If you have any questions let me know

**Comment by xy2z** [comment]
This would require the user to set it up manually, so there shold be a guide in the docs.
First this will probably just be using env variables, later I think a sysadmin UI will be better, build in the app.

But for now it should just be possible to pass the env variables for key and secret for each login, and if they are filled show a login button on the login page.

**Comment by MJunaidAhmad** [comment]
First of all great work!
I wanted to contribute to this project. Feels like an awesome app.
I will work with it this weekend. So far I am clear about this particular issue but I will get in touch if stuck somewhere. 
Thanks :)

**Comment by xy2z** [comment]
@MJunaidAhmad thanks for the kind words :)
And awesome! let me know if you have questions

**Comment by Ahamisi** [comment]
Okk I would love to make a pull request
