### ISSUE TITLE
Export notes

### ISSUE THREAD

**Issue by xy2z** [xy2z/dopenote#109]
I think the best option will be to export each note as a `.html` file in a single zipped file.

It would be nice if each note was put in a directory for each notebook, and trashed notes put in a "trash" 

The "Export notes" link should be under "User settings"

Please only do this if you have experience with this, as is could be a potential security vulnerability if the files aren't deleted or the zip isn't deleted after download, etc. I think the best option is the put the file content directly in the zip in memory without saving it to the store, but I haven't researched if it's possible, or could lead to memory issues.

Let me know if you have any questions - I'm open to other solutions

**Comment by MJunaidAhmad** [comment]
Working on this one too. :)
Will discuss security related issues with you on discard and will plan accordingly what approach would be best.
