### ISSUE TITLE
500 server error

### ISSUE THREAD

**Issue by ognjen-petrovic** [xy2z/dopenote#119]
Hi,
It often happens that a server crashes when a user presses keys quickly, hold down backspace key...

![image](https://user-images.githubusercontent.com/3530586/65950842-2e28a900-e43f-11e9-87a2-8bf8cb0f014d.png)

I intend to add some debounce in order to avoid saving content on every update. What do you think?

**Comment by xy2z** [comment]
Good idea 👍
