### ISSUE TITLE
Sort Notebook (order)

### ISSUE THREAD

**Issue by xy2z** [xy2z/dopenote#20]
Sort the order of the Notebook in the sidebar.

The best UX is to have drag and drop IMO.

**Comment by calvinmorett** [comment]
Is there somewhere where I can find, where it communicates the order of the items listed?

**Comment by xy2z** [comment]
Its in the vue data object under notebooks[0].sort_order etc

**Comment by xy2z** [comment]
Maybe we can use this https://github.com/rawilk/vue-context

**Comment by xy2z** [comment]
I went with https://github.com/johndatserakis/vue-simple-context-menu instead of "vue-context" since the other seemed only to support Node.

Context menu for notebooks are now implemented with no actions.
I'm looking into Vue.Draggable next

**Comment by xy2z** [comment]
Done
