### ISSUE TITLE
Starred view

### ISSUE THREAD

**Issue by xy2z** [xy2z/dopenote#22]
A view with only Starred notes - from all notebooks.

This should probably also be the default view when opening the webapp.

**Comment by calvinmorett** [comment]
I think showing what notebook they are in is a great frame of reference, in case there is overlapping note titles.

Notebook A > Note 3
Notebook B > Note 7
Notebook C > Note 1

**Comment by xy2z** [comment]
Good point!

**Comment by xy2z** [comment]
Works. The UI will probably be change later.
