### ISSUE TITLE
Rich-text editor

### ISSUE THREAD

**Issue by xy2z** [xy2z/dopenote#26]
Consider changing to https://tiptap.scrumpy.io/

**Comment by xy2z** [comment]
Is dark theme required? I don't think tiptap has support for dark themes, and the icons are SVG

**Comment by xy2z** [comment]
I'm working on implemented Quill (quilljs.com), as it's Open Source and seems to have most of my requirements - and can extended...

**Comment by xy2z** [comment]
Also need this extension https://github.com/patleeman/quill-markdown-shortcuts

**Comment by calvinmorett** [comment]
> Is dark theme required? I don't think tiptap has support for dark themes, and the icons are SVG

Could do a slight work around with SVGs, _Using inline SVGs with currentColor to fix the issue._

Full article: https://hiddedevries.nl/en/blog/2018-12-24-making-single-color-svg-icons-work-in-dark-mode

Examples: _original link_ https://codepen.io/hidde/pen/BvpQOZ
_my fork, with background toggle:_ https://codepen.io/CalvinMorett/full/NQPBzm

**Comment by xy2z** [comment]
I think I'm still going with Quill since it has built-in support for most of my requirements

**Comment by calvinmorett** [comment]
Looks perfect

**Comment by xy2z** [comment]
It was, until I found out i cant replace content by HTML, i have to use their objects, which would make it harder to change later... Hmm.. I have yet to find a good editor 😞

**Comment by calvinmorett** [comment]
I have no experience with any of these, but some interesting options:
- https://jaredreich.com/pell/ | https://github.com/jaredreich/pell
- https://github.com/ckeditor/ckeditor-dev
- https://github.com/mycolorway/simditor 
- https://alex-d.github.io/Trumbowyg/

**Comment by xy2z** [comment]
Thanks I didn't knew these, except ckeditor


A quick test:
Pell
- I can't open links, not even edit them.

CKeditor
I can't figure out if it's still free, and I can add it to this project without problem? They used to be open-source and free, but Im not sure anymore. https://ckeditor.com/pricing/

Simditor
- Doesn't automatically make a bullet list (<ul>) when you type "- test"
- I can't open links, only edit them.

Trumbowyg
- Same as Simditor


The reason I want to switch from Tinymce is it's kinda buggy and doesn't have support for Markdown shortcuts - like typing '# Hello' and it turns into a h1 (like Dropbox Paper) - 

But maybe that's just the best for now, and we can change it later... I just know this will be a huge part of the app, so it should be extendable for uploading images/files and more stuff. So the simple ones might not cut it.

**Comment by calvinmorett** [comment]
What are you willing to sacrifice if you can't have everything? 

Or have you considered, just a Markdown editor tab and a HTML Rich Text Editor, w/ a simple preference for which tab that should start opened as default.

**Comment by xy2z** [comment]
As long as its extendable we can always add more features later.
Right now im good with h1,h2,B,U,I, lists and links.. thats the bare minimum right?

Maybe I'll try out tinymce again, right now it may be the best...

**Comment by xy2z** [comment]
And a markdown editor is not a bad idea, but im not sure how it would work if you toggle between markdown and rich text, and something isnt supported in markdown, like Youtube videos or alignment etc. 

But maybe we can make it a user setting to toggle the toolbar and have support for markdown shortcuts (like Dropbox Paper), so its always the same editor

**Comment by calvinmorett** [comment]
> Right now im good with h1,h2,B,U,I, lists and links.. thats the bare minimum right?

blockquote & code

**Comment by xy2z** [comment]
True

Okay we can definitely rule out TinyMCE
- They require "Product Attribution"
- Some plugins are premium. https://www.tiny.cloud/pricing

So right now I think it's down to Tiptap or Quill.
Tiptap seems like the better user experience imo. So I'll  try to figure out how to implement it, I'm not really familiar with Vue Compenents...

**Comment by calvinmorett** [comment]
Quill looks easy to add, but how difficult is it to implement to other parts you've already created?

And I'm not familiar with Vue components either, but it would be a good learning experience for me to try and come up with a solution with Tiptap.

**Comment by xy2z** [comment]
Quill would be easy to add if we follow their way of adding content which is objects instead of a HTML string. This means if we want to change to another editor later, it will be very difficult since all data is saved as quilll objects instead of pure html.

So yeah let's try to get Tiptap working, it will be a good learning experience for both of us then :)

**Comment by xy2z** [comment]
Yesterday I got it working in a standalone test project :)
So next up I'll try to get it implemented in this laravel project, and I'll make the toolbar as `<button>`s (like `<button>B</button>` for bold, so it can be styled afterwards.

**Comment by xy2z** [comment]
Doesnt look bad, but i dont think its free.
From their npm page

> This is a commercial product and requires a paid license for possession or use.

**Comment by xy2z** [comment]
Tiptap added.
