### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by xy2z** [xy2z/dopenote#53]
- [ ] About
- [ ] setting up
- [x] Contribution
- [x] Code standard

I will use Gitbooks for now, maybe with github repo so people can make PRs..

**Comment by calvinmorett** [comment]
I have a related question that I do not believe requires a new issue, but if it does, let me know and I'll create it.

I own a domain name datanote.app

Would you like to us this for this instead of Dopenote?

**Comment by xy2z** [comment]
Thanks but i think the domain should match the project name

**Comment by calvinmorett** [comment]
Okay just wondering if you were interested! It’s on the table
