### ISSUE TITLE
Add tooltips on icons

### ISSUE THREAD

**Issue by xy2z** [xy2z/dopenote#62]
Note action icons (star, delete, restore, perm delete) already have `title` set, but a tooltip would be better since it's shown instantly.
It should be set on all elements with `note-action` class.

Consider
- https://github.com/FezVrasta/popper.js/
- https://atomiks.github.io/tippyjs/

Both are active

**Comment by calvinmorett** [comment]
- popper.js is a dependency of tippy

```
new Tippy('.note-action',{
  position:'top',
  arrow:'false',
  theme:'dark',
  size: 'small',
  hideOnClick: 'true'
});
```

Added

**Comment by calvinmorett** [comment]
Sorry wasn't trying to un-assign myself, just wanted to remove comment that it was done.

**Comment by xy2z** [comment]
no problem :)
