### ISSUE TITLE
Build Process for Local Development

### ISSUE THREAD

**Issue by calvinmorett** [xy2z/dopenote#8]
Care to give a quick run down for how to set this up?

**Comment by xy2z** [comment]
Sure! And thanks for the early interest.
I have updated the README with the requirements and setup.
Let me know if it doesn't work

**Comment by calvinmorett** [comment]
@xy2z I'm having some issues, and while I tried to correct them I'm running into a snag at step 8 that I'm not sure how to proceed past. 

- issues with this step, see the link below discussing PDOException errors with laravel/Illuminate
https://stackoverflow.com/questions/25329302/laravel-error-pdoexception-could-not-find-driver-in-postgresql

I'm going to go fresh and remove everything and tackle it again to see if I run into the same problem. Maybe you have knowledge to fix this step though.

**Comment by xy2z** [comment]
Can you pose the error you're getting? The link you sent is about postgresql.
Maybe you're missing the pdo mysql driver for php? If so, enable it in your php.ini under extensions

**Comment by calvinmorett** [comment]
Solved, `php artisan migrate:fresh` was returning `PDOException::("could not find driver")`

To solve it, leave `extension=php_pdo_mysql.dll` uncommented it from php.ini in xampp/php and the main php install

**Comment by calvinmorett** [comment]
Would like to reopen the issue to talk about the build process and how I think the versions should be listed.

**Comment by xy2z** [comment]
What are you thinking?

**Comment by calvinmorett** [comment]
Just need current php version listed and gtg!
